### ISSUE TITLE
Crash on lollipop (5.0.2 abd 5.1.1) when calling OIDCAccountManager.getAccessToken

### ISSUE THREAD

**Issue by abdulrahimallana** [kalemontes/OIDCAndroidLib#12]
The following crash occurs on two different devices running lollipop:

```
com.myapp E/SensitiveDataStorage: Can't decrypt data
	org.spongycastle.crypto.InvalidCipherTextException: pad block corrupted
		at org.spongycastle.crypto.paddings.PKCS7Padding.padCount(PKCS7Padding.java:72)
		at org.spongycastle.crypto.paddings.PaddedBufferedBlockCipher.doFinal(PaddedBufferedBlockCipher.java:287)
		at com.lnikkila.oidc.security.SensitiveDataPreApi23.cipherData(SensitiveDataPreApi23.java:132)
		at com.lnikkila.oidc.security.SensitiveDataPreApi23.decrypt(SensitiveDataPreApi23.java:196)
		at com.lnikkila.oidc.security.SensitiveDataUtils.decrypt(SensitiveDataUtils.java:94)
		at com.lnikkila.oidc.security.AccountSensitiveDataStorageUtils.retrieveStringData(AccountSensitiveDataStorageUtils.java:66)
		at com.lnikkila.oidc.OIDCAccountManager.getToken(OIDCAccountManager.java:169)
		at com.lnikkila.oidc.OIDCAccountManager.getAccessToken(OIDCAccountManager.java:148)
		at com.myapp.activity.BaseActivity.getAccountToken(BaseActivity.java:108)
		at com.myapp.activity.HomeActivity$5.intercept(HomeActivity.java:283)
		at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:190)
		at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:212)
		at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:190)
		at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:163)
		at okhttp3.RealCall.execute(RealCall.java:57)
		at com.myapp.activity.HomeActivity$4.doInBackground(HomeActivity.java:204)
		at com.myapp.activity.HomeActivity$4.doInBackground(HomeActivity.java:169)
		at android.os.AsyncTask$2.call(AsyncTask.java:292)
		at java.util.concurrent.FutureTask.run(FutureTask.java:237)
		at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
		at java.lang.Thread.run(Thread.java:818)
```

Device details, Samsun galaxy j1 (5.1.1) and Samsung galaxy tab s 10.5 (5.0.2)

**Comment by kalemontes** [comment]
I have a little idea of what this is. I'll try to fixe it soon.

**Comment by abdulrahimallana** [comment]
I have tinkered and found the issue and fixed it locally. The issue was that pre-marshmallow the library would generate a new secret key on instantiation, instead of loading a pre-existing one. I could fork and do a pull request with a fix if you like.  Or you could fix in your own time when you get a chance

**Comment by kalemontes** [comment]
Please make a pull request i'll be glad to merge.

**Comment by jimmytrivedi** [comment]
Any update on this?

**Comment by kalemontes** [comment]
Hi @jimmytrivedi I stopped maintaining this lib. There are new standards (NAPPS) so I recommend you take a look on https://github.com/openid/AppAuth-Android instead.
